apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway
  namespace: nginx-gateway
spec:
  type: NodePort 
  ports:
  - port: 80
    nodePort: 30303
    protocol: TCP
    name: http
  selector:
    app: nginx-gateway
