apiVersion: apps/v1
kind: Deployment
metadata:
  name: illegal-dump-api-gateway-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-mock-v1
  template:
    metadata:
      labels:
        app: api-gateway-mock-v1
    spec:
      containers:
      - name: mock
        image: kw4si0r/illegal-dump-api-gateway-mock
        ports:
        - containerPort: 1080

---

apiVersion: v1
kind: Service
metadata:
  name: illegal-dump-api-gateway-mock
spec:
  # type: NodePort
  ports:
  - port: 1080
    targetPort: 1080
    # nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: api-gateway-mock-v1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: illegal-dump-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: illegal-dump-webapp
  template:
    metadata:
      labels:
        app: illegal-dump-webapp
    spec:
      containers:
      - name: webapp
        image: kw4si0r/illegal-dump-webapp
        ports:
        - containerPort: 80
        - containerPort: 30303
        env:
          - name: API_GATEWAY_URL
            value: http://illegal-dump-api-gateway-mock:1080
            

---

apiVersion: v1
kind: Service
metadata:
  name: illegal-dump-webapp
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30081
    protocol: TCP
    name: http 
  - port: 30303
    nodePort: 30303
    protocol: TCP
    name: proxy 
  selector:
    app: illegal-dump-webapp
