apiVersion: apps/v1
kind: Deployment
metadata:
  name: illegal-dump-coordinates
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coordinates
  template:
    metadata:
      labels:
        app: coordinates
    spec:
      containers:
        - name: coordinates
          image: kw4si0r/illegal-dump-coordinates
          ports:
            - containerPort: 8061
          env:
            - name: QUARKUS_PROFILE
              value: prd-k8
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1"
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8061
            initialDelaySeconds: 2
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8061
            initialDelaySeconds: 30
            periodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: illegal-dump-coordinates
spec:
  type: NodePort
  ports:
    - port: 8061
#      targetPort: 8061
      nodePort: 30061
      protocol: TCP
      name: http
  selector:
    app: coordinates