persistence:
  #By setting it to false we can disable the persistence so that after uninstalling the helm release, the data is not persisted
  enabled: false

primary:
  initdb:
    scripts:
      db-init.sql: |
        CREATE ROLE "coordinates" WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION CONNECTION LIMIT -1 PASSWORD 'Dr52PdrY8_1D3';
        CREATE TABLESPACE "ts_db1" OWNER coordinates LOCATION '/bitnami/postgresql/data/';
        ALTER TABLESPACE "ts_db1" OWNER TO coordinates;
        CREATE DATABASE db1 WITH OWNER = coordinates ENCODING = 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8' TABLESPACE = "ts_db1" CONNECTION LIMIT = -1 IS_TEMPLATE = False;
        

